export const artworks = [
  {
    slug: 'bohemian-forest-5',
    title: 'Bohemian Forest 5',
    year: '2025',
    medium: 'Acrylic on canvas',
    size: '150 × 200 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Bohemian-Forest-5-2025-150x200-cm-acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'bride',
    title: 'Bride',
    year: '2025',
    medium: 'Acrylic on canvas',
    size: '60 × 50 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Bride-2025-60x50cm-acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'upside-down',
    title: 'Upside Down',
    year: '2025',
    medium: 'Acrylic on canvas',
    size: '130 × 100 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Upside-down-2025-130x100-cm-acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'red-coast',
    title: 'Red Coast',
    year: '2025',
    medium: 'Acrylic on canvas',
    size: '60 × 50 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Red-Coast-2025-60x50-cm-acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'fragility',
    title: 'Fragility',
    year: '2024',
    medium: 'Acrylic on canvas',
    size: '130 × 100 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Fragility-2024-130x100-cm-acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'heartbeats',
    title: 'Heartbeats',
    year: '2024',
    medium: 'Acrylic on canvas',
    size: '120 × 100 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Heartbeats-2024-120x100-cm-acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'i-need-the-night',
    title: 'I Need The Night',
    year: '2024',
    medium: 'Acrylic on canvas',
    size: '130 × 100 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/I-Need-The-Night-2024-130-x100-cm-acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'their-love',
    title: 'Their Love',
    year: '2024',
    medium: 'Acrylic on canvas',
    size: '80 × 60 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Their-Love-2024-80x60cm-acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'colored-moments',
    title: 'Colored Moments',
    year: '2024',
    medium: 'Acrylic on canvas',
    size: '100 × 100 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Colored-Moments-2024-100x100-cm-acrylic-on-canvas.jpg',
    ar: true,
    glb: '/assets/colored-moments.glb',
    usdz: '/assets/colored-moments.usdz',
    poster: '/assets/colored-moments-texture.png',
  },
  {
    slug: 'all-my-boats',
    title: 'All My Boats',
    year: '2024',
    medium: 'Acrylic on canvas',
    size: '120 × 100 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/All-My-Boats-2024-120x100-cm-acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'fisher-island-sound',
    title: 'Fisher Island Sound',
    year: '2024',
    medium: 'Acrylic on canvas',
    size: '100 × 100 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Fisher-Island-Sound-2024-100x100-cm-acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'mermaid',
    title: 'Mermaid',
    year: '2024',
    medium: 'Acrylic on canvas',
    size: '150 × 100 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Mermaid_2024_150x100cm_acrylic-on-canvas.jpg',
    ar: false,
  },
];

export const featuredArtwork = artworks[0];
export const arArtwork = artworks.find((artwork) => artwork.slug === 'colored-moments');
