export const artworks = [
  {
    slug: 'bohemian-forest-5',
    title: 'Bohemian Forest 5',
    year: '2025',
    medium: 'Acrylic on canvas',
    size: '150 × 200 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Bohemian-Forest-5-2025-150x200-cm-acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'bride',
    title: 'Bride',
    year: '2025',
    medium: 'Acrylic on canvas',
    size: '60 × 50 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Bride-2025-60x50cm-acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'saint-sebastian-with-plastic-arrows',
    title: 'Saint Sebastian with Plastic Arrows',
    year: '2025',
    medium: 'Acrylic on canvas',
    size: '',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Saint-Sebastian-with-plastic-arrows-2025-60x50-cm-acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'upside-down',
    title: 'Upside Down',
    year: '2025',
    medium: 'Acrylic on canvas',
    size: '130 × 100 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Upside-down-2025-130x100-cm-acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'red-coast',
    title: 'Red Coast',
    year: '2025',
    medium: 'Acrylic on canvas',
    size: '',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Red-Coast-2025-60x50-cm-acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'fragility',
    title: 'Fragility',
    year: '2024',
    medium: 'Acrylic on canvas',
    size: '130 × 100 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Fragility-2024-130x100-cm-acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'heartbeats',
    title: 'Heartbeats',
    year: '2024',
    medium: 'Acrylic on canvas',
    size: '120 × 100 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Heartbeats-2024-120x100-cm-acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'i-need-the-night',
    title: 'I Need The Night',
    year: '2024',
    medium: 'Acrylic on canvas',
    size: '130 × 100 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/I-Need-The-Night-2024-130-x100-cm-acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'their-love',
    title: 'Their Love',
    year: '2024',
    medium: 'Acrylic on canvas',
    size: '80 × 60 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Their-Love-2024-80x60cm-acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'colored-moments',
    title: 'Colored Moments',
    year: '2024',
    medium: 'Acrylic on canvas',
    size: '100 × 100 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Colored-Moments-2024-100x100-cm-acrylic-on-canvas.jpg',
    ar: true,
    glb: '/assets/colored-moments.glb',
    usdz: '/assets/colored-moments.usdz',
    poster: '/assets/colored-moments.jpg',
  },
  {
    slug: 'all-my-boats',
    title: 'All My Boats',
    year: '2024',
    medium: 'Acrylic on canvas',
    size: '120 × 100 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/All-My-Boats-2024-120x100-cm-acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'fisher-island-sound',
    title: 'Fisher Island Sound',
    year: '2024',
    medium: 'Acrylic on canvas',
    size: '',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Fisher-Island-Sound-2024-100x100-cm-acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'mermaid',
    title: 'Mermaid',
    year: '2024',
    medium: 'Acrylic on canvas',
    size: '150 × 100 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Mermaid_2024_150x100cm_acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'red-house',
    title: 'Red House',
    year: '2024',
    medium: 'Acrylic on canvas',
    size: '120 × 100 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Red-House_2024_120x100-cm_acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'dream-about-renoir',
    title: 'Dream About Renoir',
    year: '2024',
    medium: 'Acrylic on canvas',
    size: '100 × 100 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Dream-About-Renoir_2024_100x100-cm_acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'conversation',
    title: 'Conversation',
    year: '2024',
    medium: 'Acrylic on canvas',
    size: '150 × 300 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Conversation_2024_150x300cm_acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'evening-walk-along-the-sea-that-never-freezes',
    title: 'Evening Walk Along The Sea That Never Freezes',
    year: '2024',
    medium: 'Acrylic on canvas',
    size: '60 × 50 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Evening-Walk-Along-The-Sea-That-Never-Freezes_2024_60x50-cm_acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'albatross',
    title: 'Albatross',
    year: '2024',
    medium: 'Acrylic on canvas',
    size: '60 × 50 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Albatross_2024_60x50-cm_acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'fallen-suns',
    title: 'Fallen Suns',
    year: '2024',
    medium: 'Acrylic on canvas',
    size: '80 × 60 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Fallen-Suns_2024_80x60-cm_acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'pocket-museum-yellow-version',
    title: 'Pocket Museum Yellow Version',
    year: '2024',
    medium: 'Acrylic on canvas',
    size: '140 × 100 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Pocket-Museum-Yellow-Version_2024_140x100-cm_acrylic-on-canvas.jpg',
    ar: false,
  },
  {
    slug: 'two-dogs-inside',
    title: 'Two Dogs Inside',
    year: '2024',
    medium: 'Acrylic on canvas',
    size: '130 × 100 cm',
    image: 'https://jirihauschka.com/wp-content/uploads/2025/03/Two-Dogs-Inside-2024-130x100-cm-acrylic-on-canvas.jpg',
    ar: false,
  },
];

export const featuredArtwork = artworks[0];
export const arArtwork = artworks.find((a) => a.slug === 'colored-moments');
export const artworkBySlug = (slug) => artworks.find((a) => a.slug === slug);
